# Complete PyTorch Tensor Guide


---

## Table of Contents

1. [What is a Tensor?](#what-is-a-tensor)
2. [Tensor Types by Dimension](#tensor-types)
3. [Why Are Tensors Useful?](#why-tensors)
4. [Creating Tensors](#creating-tensors)
5. [Tensor Operations](#tensor-operations)
6. [Reshaping & Indexing](#reshaping)
7. [GPU Operations](#gpu-operations)

---

## Setup & Environment Check

In [42]:
# ALWAYS RUN THIS FIRST
import os
os.environ['CUDA_LAUNCH_BLOCKING'] = '1'

In [43]:
import torch
import numpy as np

print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")

if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    print(f"Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB")
    device = torch.device('cuda')
else:
    print("Running on CPU")
    device = torch.device('cpu')

PyTorch version: 2.5.1+cu121
CUDA available: True
GPU: NVIDIA GeForce RTX 4060 Laptop GPU
Memory: 8.33 GB


---

# PART 1: Understanding Tensors

---

<a id='what-is-a-tensor'></a>
## What is a Tensor?

A **tensor** is a multi-dimensional array of numbers. It's the fundamental data structure used in deep learning and numerical computing.

Think of tensors as:
- **Scalars** (0D): A single number
- **Vectors** (1D): A list of numbers
- **Matrices** (2D): A table of numbers
- **Higher dimensions** (3D+): Stacked matrices

<a id='tensor-types'></a>
## Tensor Types by Dimension

### 0D Tensor - Scalar
A single number.

**Properties:**
- Shape: `()`
- Rank: 0
- Use cases: Loss function value(forward path) etc

---

### 1D Tensor - Vector
A list of numbers in a single direction.

**Properties:**
- Shape: `(n,)`
- Rank: 1
- Use cases: Feature vector, time series, word embedding

---

### 2D Tensor - Matrix
A table with rows and columns.

**Properties:**
- Shape: `(rows, cols)`
- Rank: 2
- Use cases: Grayscale image, spreadsheet, weight matrix

---

### 3D Tensor
A cube of numbers - stacked matrices.

**Properties:**
- Shape: `(depth, height, width)` or `(height, width, channels)`
- Rank: 3
- Use cases: RGB image, sequence of vectors

---

### 4D Tensor
Batch of 3D tensors.

**Properties:**
- Shape: `(batch, channels, height, width)` or `(batch, height, width, channels)`
- Rank: 4
- Use cases: Batch of images, video frames

---

### 5D+ Tensors
Specialized applications.

**Examples:**
- **5D**: Video batches `(batch, time, height, width, channels)`
- **6D+**: Scientific simulations

In [44]:
# Examples of different tensor dimensions

# 0D - Scalar
scalar = torch.tensor(42)
print(f"Scalar: {scalar}, Shape: {scalar.shape}, Rank: {scalar.ndim}")

# 1D - Vector
vector = torch.tensor([1, 2, 3, 4, 5])
print(f"\nVector: {vector}")
print(f"Shape: {vector.shape}, Rank: {vector.ndim}")

# 2D - Matrix / gray scale image
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(f"\nMatrix:\n{matrix}")
print(f"Shape: {matrix.shape}, Rank: {matrix.ndim}")

# 3D - RGB Image
image_3d = torch.rand(224, 224, 3)  # Height x Width x Channels
print(f"\n3D Tensor (RGB Image): Shape: {image_3d.shape}, Rank: {image_3d.ndim}")

# 4D - Batch of images
batch_images = torch.rand(32, 3, 224, 224)  # Batch x Channels x Height x Width
print(f"\n4D Tensor (Image Batch): Shape: {batch_images.shape}, Rank: {batch_images.ndim}")

Scalar: 42, Shape: torch.Size([]), Rank: 0

Vector: tensor([1, 2, 3, 4, 5])
Shape: torch.Size([5]), Rank: 1

Matrix:
tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3]), Rank: 2

3D Tensor (RGB Image): Shape: torch.Size([224, 224, 3]), Rank: 3

4D Tensor (Image Batch): Shape: torch.Size([32, 3, 224, 224]), Rank: 4


### Common Tensor Shapes in Machine Learning

| Application | Typical Shape | Meaning |
|-------------|---------------|------|
| **Single grayscale image** | `(28, 28)` | 28×28 pixels |
| **Single RGB image** | `(224, 224, 3)` | 224×224 pixels, 3 channels |
| **Batch of images** | `(32, 3, 224, 224)` | 32 images, 3 channels, 224×224 |
| **Text sequence** | `(100, 512)` | 100 tokens, 512-dim embeddings |
| **Batch of sequences** | `(16, 100, 512)` | 16 sequences in batch |
| **Video clip** | `(30, 720, 1280, 3)` | 30 frames, 720p resolution |

<a id='why-tensors'></a>
## Why Are Tensors Useful?

### 1. Mathematical Operations
- **Vectorized computations**: Process entire arrays at once
- **Fast parallel computation**: Essential for deep learning
- **Automatic differentiation**: Built-in gradient tracking

### 2. Representation of Real-world Data
- **Images**: 3D tensors (height × width × channels)
- **Text**: 2D/3D tensors (sequence × embedding)
- **Audio**: 2D/3D tensors (time × features)
- **Video**: 4D tensors (frames × height × width × channels)

### 3. Hardware Acceleration
- **GPU/TPU optimized**: 40x-100x faster than CPU
- **Parallel processing**: Thousands of operations simultaneously
- **Reduced training time**: Weeks → hours

## Where Tensors Are Used in Deep Learning

1. **Data Storage**: Training data (images, text, audio)
2. **Model Parameters**: Weights and biases
3. **Computations**: Matrix operations, convolutions
4. **Gradients**: Backpropagation derivatives
5. **Outputs**: Model predictions and activations

---

# PART 2: Creating Tensors

---

<a id='creating-tensors'></a>
## Creating Tensors - All Methods

### 1. From Python Lists/Arrays

In [45]:
# From Python list
t1 = torch.tensor([1, 2, 3, 4, 5])
print(f"From list: {t1}",t1.ndim)

# From nested list (2D)
t2 = torch.tensor([[1, 2], [3, 4], [5, 6]])
print(f"\nFrom 2D list:\n{t2}", t2.ndim)

# From NumPy array
arr = np.array([1, 2, 3, 4])
t3 = torch.from_numpy(arr)
print(f"\nFrom NumPy: {t3}")

# As tensor (shares memory with NumPy)
t4 = torch.as_tensor(arr)
print(f"As tensor: {t4}")

From list: tensor([1, 2, 3, 4, 5]) 1

From 2D list:
tensor([[1, 2],
        [3, 4],
        [5, 6]]) 2

From NumPy: tensor([1, 2, 3, 4])
As tensor: tensor([1, 2, 3, 4])


### 2.  empty ,Zeros, Ones, and Fill

In [46]:
#empty
empty = torch.empty(2, 3)   
print(f"Empty (2x3):\n{empty}")

# Zeros
zeros = torch.zeros(3, 4)
print(f"Zeros (3x4):\n{zeros}")

# Ones
ones = torch.ones(2, 3)
print(f"\nOnes (2x3):\n{ones}")

# Fill with specific value
sevens = torch.full((3, 3), 7)
print(f"\nFilled with 7:\n{sevens}")

# Like another tensor
reference = torch.rand(2, 2)
zeros_like = torch.zeros_like(reference)
print(f"\nZeros like another tensor:\n{zeros_like}")

#ones like
ones_like = torch.ones_like(reference)
print(f"\nOnes like another tensor:\n{ones_like}")

# Full like
full_like = torch.full_like(reference, 5)
print(f"\nFull like another tensor (filled with 5):\n{full_like}")

Empty (2x3):
tensor([[-5.5581e+37,  3.4510e-41,  0.0000e+00],
        [ 0.0000e+00, -1.5532e+03,  4.3544e-41]])
Zeros (3x4):
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

Ones (2x3):
tensor([[1., 1., 1.],
        [1., 1., 1.]])

Filled with 7:
tensor([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]])

Zeros like another tensor:
tensor([[0., 0.],
        [0., 0.]])

Ones like another tensor:
tensor([[1., 1.],
        [1., 1.]])

Full like another tensor (filled with 5):
tensor([[5., 5.],
        [5., 5.]])


### 3. Random Tensors

In [47]:
# Uniform distribution [0, 1)
rand_uniform = torch.rand(3, 3)
print(f"Random uniform [0,1):\n{rand_uniform}")

# Normal distribution (mean=0, std=1)
rand_normal = torch.randn(3, 3)
print(f"\nRandom normal (μ=0, σ=1):\n{rand_normal}")

# Random integers
rand_int = torch.randint(0, 20, (3, 3))
print(f"\nRandom integers [0-10):\n{rand_int}")

# Random permutation
perm = torch.randperm(10)
print(f"\nRandom permutation: {perm}")

Random uniform [0,1):
tensor([[0.2152, 0.6040, 0.2190],
        [0.2177, 0.3105, 0.8013],
        [0.6136, 0.8432, 0.2830]])

Random normal (μ=0, σ=1):
tensor([[ 0.9315, -1.9030, -0.6151],
        [-0.6052,  1.0670,  2.0670],
        [ 0.4866, -0.1337, -0.3534]])

Random integers [0-10):
tensor([[17, 19, 17],
        [19, 16,  5],
        [16,  5, 16]])

Random permutation: tensor([8, 0, 6, 3, 4, 2, 1, 7, 5, 9])


### 4. Sequential Tensors

In [48]:
# Range with step
arange_tensor = torch.arange(0, 10, 2)
print(f"Arange [0, 10) step 2: {arange_tensor}")

# Linearly spaced
linspace_tensor = torch.linspace(0, 1, 5)
print(f"\nLinspace [0, 1] 5 points: {linspace_tensor}")

# Logarithmically spaced
logspace_tensor = torch.logspace(0, 2, 5)
print(f"\nLogspace [10^0, 10^2]: {logspace_tensor}")

Arange [0, 10) step 2: tensor([0, 2, 4, 6, 8])

Linspace [0, 1] 5 points: tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

Logspace [10^0, 10^2]: tensor([  1.0000,   3.1623,  10.0000,  31.6228, 100.0000])


### 5. Special Matrices

In [49]:
# Identity matrix
identity = torch.eye(4)
print(f"Identity matrix (4x4):\n{identity}")

# Diagonal matrix
diag = torch.diag(torch.tensor([1, 2, 3, 4]))
print(f"\nDiagonal matrix:\n{diag}")

# Empty (uninitialized - faster but contains garbage)
empty = torch.empty(2, 3)
print(f"\nEmpty tensor (garbage values):\n{empty}")

Identity matrix (4x4):
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

Diagonal matrix:
tensor([[1, 0, 0, 0],
        [0, 2, 0, 0],
        [0, 0, 3, 0],
        [0, 0, 0, 4]])

Empty tensor (garbage values):
tensor([[1.3948e-36, 3.4506e-41, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


### 6. Specifying Data Types

In [50]:
# Integer types
int32 = torch.tensor([1, 2, 3], dtype=torch.int32)
int64 = torch.tensor([1, 2, 3], dtype=torch.int64)  # long

# Float types
float32 = torch.tensor([1.0, 2.0], dtype=torch.float32)  # float
float64 = torch.tensor([1.0, 2.0], dtype=torch.float64)  # double
float16 = torch.tensor([1.0, 2.0], dtype=torch.float16)  # half precision

# Boolean
bool_tensor = torch.tensor([True, False, True], dtype=torch.bool)

print(f"int32: {int32}, dtype: {int32.dtype}")
print(f"float32: {float32}, dtype: {float32.dtype}")
print(f"float16: {float16}, dtype: {float16.dtype}")
print(f"bool: {bool_tensor}, dtype: {bool_tensor.dtype}")

int32: tensor([1, 2, 3], dtype=torch.int32), dtype: torch.int32
float32: tensor([1., 2.]), dtype: torch.float32
float16: tensor([1., 2.], dtype=torch.float16), dtype: torch.float16
bool: tensor([ True, False,  True]), dtype: torch.bool


### 7. Specifying Device (CPU/GPU)

In [51]:
# On CPU
cpu_tensor = torch.randn(3, 3, device='cpu')
print(f"CPU tensor device: {cpu_tensor.device}")

# On GPU (if available)
if torch.cuda.is_available():
    gpu_tensor = torch.randn(3, 3, device='cuda')
    print(f"GPU tensor device: {gpu_tensor.device}")
    
    # Move between devices
    cpu_to_gpu = cpu_tensor.to('cuda')
    gpu_to_cpu = gpu_tensor.to('cpu')
    
    print(f"Moved to GPU: {cpu_to_gpu.device}")
    print(f"Moved to CPU: {gpu_to_cpu.device}")
else:
    print("GPU not available")

CPU tensor device: cpu
GPU tensor device: cuda:0
Moved to GPU: cuda:0
Moved to CPU: cpu


---

# PART 3: Tensor Operations

---

<a id='tensor-operations'></a>
## Basic Arithmetic Operations

In [52]:
a = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
b = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

print(f"Tensor a:\n{a}")
print(f"\nTensor b:\n{b}")

# Element-wise operations
print(f"\na + b:\n{a + b}")
print(f"\na - b:\n{a - b}")
print(f"\na * b (element-wise):\n{a * b}")
print(f"\na / b:\n{a / b}")
print(f"\na ** 2:\n{a ** 2}")

Tensor a:
tensor([[1., 2.],
        [3., 4.]])

Tensor b:
tensor([[5., 6.],
        [7., 8.]])

a + b:
tensor([[ 6.,  8.],
        [10., 12.]])

a - b:
tensor([[-4., -4.],
        [-4., -4.]])

a * b (element-wise):
tensor([[ 5., 12.],
        [21., 32.]])

a / b:
tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])

a ** 2:
tensor([[ 1.,  4.],
        [ 9., 16.]])


## Matrix Operations

In [53]:
# Matrix multiplication
matmul = torch.matmul(a, b)  # or a @ b
print(f"Matrix multiplication (a @ b):\n{matmul}")

# Transpose
print(f"\nTranspose of a:\n{a.T}")

# Dot product (1D only)
v1 = torch.tensor([1, 2, 3], dtype=torch.float32)
v2 = torch.tensor([4, 5, 6], dtype=torch.float32)
dot = torch.dot(v1, v2)
print(f"\nDot product: {dot}")

Matrix multiplication (a @ b):
tensor([[19., 22.],
        [43., 50.]])

Transpose of a:
tensor([[1., 3.],
        [2., 4.]])

Dot product: 32.0


## Aggregation Operations

In [54]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
print(f"Tensor x:\n{x}")

print(f"\nSum: {x.sum()}")
print(f"Mean: {x.mean()}")
print(f"Max: {x.max()}")
print(f"Min: {x.min()}")
print(f"Std: {x.std()}")

# Along specific dimension
print(f"\nSum along columns (dim=0): {x.sum(dim=0)}")
print(f"Sum along rows (dim=1): {x.sum(dim=1)}")
print(f"Max indices (argmax): {x.argmax(dim=1)}")

Tensor x:
tensor([[1., 2., 3.],
        [4., 5., 6.]])

Sum: 21.0
Mean: 3.5
Max: 6.0
Min: 1.0
Std: 1.8708287477493286

Sum along columns (dim=0): tensor([5., 7., 9.])
Sum along rows (dim=1): tensor([ 6., 15.])
Max indices (argmax): tensor([2, 2])


## In-place Operations

Operations ending with `_` modify the tensor in-place (faster, saves memory)

In [55]:
m = torch.rand(2, 3)
print(f"Original:\n{m}")

# In-place addition
m.add_(5)
print(f"\nAfter add_(5):\n{m}")

# In-place multiplication
m.mul_(2)
print(f"\nAfter mul_(2):\n{m}")

# In-place ReLU
m = torch.randn(2, 3)
print(f"\nBefore ReLU:\n{m}")
m.relu_()
print(f"After ReLU:\n{m}")

Original:
tensor([[0.2288, 0.8842, 0.9079],
        [0.6800, 0.2674, 0.7224]])

After add_(5):
tensor([[5.2288, 5.8842, 5.9079],
        [5.6800, 5.2674, 5.7224]])

After mul_(2):
tensor([[10.4577, 11.7685, 11.8158],
        [11.3601, 10.5347, 11.4448]])

Before ReLU:
tensor([[-1.7119, -0.5176,  1.8698],
        [-0.7041,  1.1962, -0.3336]])
After ReLU:
tensor([[0.0000, 0.0000, 1.8698],
        [0.0000, 1.1962, 0.0000]])


---

# PART 4: Reshaping & Indexing

---

<a id='reshaping'></a>
## Reshaping Tensors

In [56]:
original = torch.arange(12)
print(f"Original (12,): {original}")

# Reshape
reshaped = original.reshape(3, 4)
print(f"\nReshaped to (3, 4):\n{reshaped}")

reshaped = original.reshape(4, 3)
print(f"\nReshaped to (4, 3):\n{reshaped}")

# View (shares memory)
viewed = original.view(4, 3)
print(f"\nViewed as (4, 3):\n{viewed}")

# Flatten
flattened = reshaped.flatten()
print(f"\nFlattened: {flattened}")

# Squeeze (remove dimensions of size 1)
squeezed = torch.ones(1, 3, 1, 4)
print(squeezed)
print(f"\nBefore squeeze: {squeezed.shape}")
print(f"After squeeze: {squeezed.squeeze().shape}")

# Unsqueeze (add dimension)
unsqueezed = torch.ones(3, 4)
print(unsqueezed)
print(f"\nBefore unsqueeze: {unsqueezed.shape}")
print(f"After unsqueeze(0): {unsqueezed.unsqueeze(0).shape}")
print(f"After unsqueeze(1): {unsqueezed.unsqueeze(1).shape}")

Original (12,): tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Reshaped to (3, 4):
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Reshaped to (4, 3):
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

Viewed as (4, 3):
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

Flattened: tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[[[1., 1., 1., 1.]],

         [[1., 1., 1., 1.]],

         [[1., 1., 1., 1.]]]])

Before squeeze: torch.Size([1, 3, 1, 4])
After squeeze: torch.Size([3, 4])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Before unsqueeze: torch.Size([3, 4])
After unsqueeze(0): torch.Size([1, 3, 4])
After unsqueeze(1): torch.Size([3, 1, 4])


## Indexing & Slicing

In [57]:
tensor = torch.arange(12).reshape(3, 4)
print(f"Tensor:\n{tensor}")

# Basic indexing
print(f"\nFirst row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Element at (1, 2): {tensor[1, 2]}")

# Slicing
print(f"\nSubmatrix [0:2, 1:3]:\n{tensor[0:2, 1:3]}")

# Boolean indexing
mask = tensor > 5
print(f"\nMask (elements > 5):\n{mask}")
print(f"Elements > 5: {tensor[mask]}")

# Fancy indexing
indices = torch.tensor([0, 2])
print(f"\nRows 0 and 2:\n{tensor[indices]}")

Tensor:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

First row: tensor([0, 1, 2, 3])
First column: tensor([0, 4, 8])
Element at (1, 2): 6

Submatrix [0:2, 1:3]:
tensor([[1, 2],
        [5, 6]])

Mask (elements > 5):
tensor([[False, False, False, False],
        [False, False,  True,  True],
        [ True,  True,  True,  True]])
Elements > 5: tensor([ 6,  7,  8,  9, 10, 11])

Rows 0 and 2:
tensor([[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]])


## Joining & Splitting Tensors

In [58]:
t1 = torch.tensor([[1, 2], [3, 4]])
t2 = torch.tensor([[5, 6], [7, 8]])

# Concatenate
cat_dim0 = torch.cat([t1, t2], dim=0)
print(f"Concatenate dim=0:\n{cat_dim0}")

cat_dim1 = torch.cat([t1, t2], dim=1)
print(f"\nConcatenate dim=1:\n{cat_dim1}")

# Stack (creates new dimension)
stacked = torch.stack([t1, t2], dim=0)
print(f"\nStacked shape: {stacked.shape}")
print(f"Stacked:\n{stacked}")

# Split
chunks = torch.chunk(cat_dim0, 2, dim=0)
print(f"\nSplit into 2 chunks:")
for i, chunk in enumerate(chunks):
    print(f"Chunk {i}:\n{chunk}")

Concatenate dim=0:
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

Concatenate dim=1:
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])

Stacked shape: torch.Size([2, 2, 2])
Stacked:
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

Split into 2 chunks:
Chunk 0:
tensor([[1, 2],
        [3, 4]])
Chunk 1:
tensor([[5, 6],
        [7, 8]])


## Copying Tensors

⚠️ **Important**: `b = a` creates a reference, not a copy!

In [59]:
a = torch.rand(2, 3)
print(f"Original a:\n{a}")

# Reference (NOT a copy)
b = a
a[0, 0] = 999
print(f"\nAfter modifying a, b is also changed:\n{b}")

# Proper copy using clone()
a = torch.rand(2, 3)
c = a.clone()
a[0, 0] = 999
print(f"\nAfter modifying a, c is NOT changed:\n{c}")
print(f"Modified a:\n{a}")

Original a:
tensor([[0.6283, 0.9068, 0.0055],
        [0.1166, 0.2034, 0.0172]])

After modifying a, b is also changed:
tensor([[9.9900e+02, 9.0677e-01, 5.4920e-03],
        [1.1658e-01, 2.0344e-01, 1.7160e-02]])

After modifying a, c is NOT changed:
tensor([[0.4639, 0.9985, 0.5250],
        [0.7920, 0.5363, 0.1187]])
Modified a:
tensor([[9.9900e+02, 9.9853e-01, 5.2500e-01],
        [7.9200e-01, 5.3627e-01, 1.1870e-01]])


---

# PART 5: GPU Operations

---

<a id='gpu-operations'></a>
## Working with GPU

GPU acceleration can provide 40x-100x speedup for tensor operations!

In [60]:
# Check GPU availability
print(f"CUDA available: {torch.cuda.is_available()}")

if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    print(f"Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.2f} GB")
    print(f"Current device: {torch.cuda.current_device()}")
    
    # Set device
    device = torch.device('cuda')
else:
    print("GPU not available, using CPU")
    device = torch.device('cpu')

CUDA available: True
GPU: NVIDIA GeForce RTX 4060 Laptop GPU
Memory: 8.33 GB
Current device: 0


In [61]:
# Create tensor on GPU
if torch.cuda.is_available():
    # Method 1: Create directly on GPU
    x = torch.randn(3, 3, device='cuda')
    print(f"Tensor on GPU: {x.device}")
    
    # Method 2: Move from CPU to GPU
    y = torch.randn(3, 3)
    y_gpu = y.to('cuda')
    # or y_gpu = y.cuda()
    print(f"Moved to GPU: {y_gpu.device}")
    
    # Operations on GPU
    z = x @ y_gpu
    print(f"\nResult on GPU: {z.device}")
    
    # Move back to CPU
    z_cpu = z.to('cpu')
    # or z_cpu = z.cpu()
    print(f"Moved to CPU: {z_cpu.device}")
    
    # Clear GPU cache
    torch.cuda.empty_cache()
    print("\nGPU cache cleared")

Tensor on GPU: cuda:0
Moved to GPU: cuda:0

Result on GPU: cuda:0
Moved to CPU: cpu

GPU cache cleared


## Best Practices

### 1. Device Management
```python
# Set device at the start
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Use everywhere
tensor = torch.randn(10, 10, device=device)
```

### 2. Memory Management
```python
# Clear GPU cache when needed
torch.cuda.empty_cache()

# Use no_grad() for inference
with torch.no_grad():
    output = model(input)
```

### 3. Debugging
```python
# Check for NaN/Inf
assert not torch.isnan(tensor).any()
assert not torch.isinf(tensor).any()

# Print stats
print(f"Min: {tensor.min()}, Max: {tensor.max()}, Mean: {tensor.mean()}")
```